version: 0.2

phases:
  pre_build:
    commands:
      - echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_DIR
  build:
    commands:
      - docker build -t $ECR_DIR:latest .
      - docker tag $ECR_DIR:latest $ECR_DIR:latest   
  post_build:
    commands:
      - docker push $ECR_DIR:latest
      - sed -i -e 's;%APPNAME%;${appName};g' -e 's;%ECRIMAGEN%;${REPO_NAME};g' aws/task-definition-ec2.json
      - sed -i -e 's;%IMAGEPORT%;${IMAGE_PORT};g'  aws/task-definition-ec2.json
      - aws ecs register-task-definition --region ${AWS_REGION} --cli-input-json file://task-definition-ec2.json 
      - aws ecs update-service --cluster ${CLUSTER_NAME} --desired-count 1 --service ${SERVICE_NAME} --region ${AWS_REGION} --task-definition ${APPNAME}